# Generated by Django 2.1.4 on 2019-09-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('md', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='gname',
            new_name='name',
        ),
    ]
