# Generated by Django 2.1.4 on 2019-09-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('md', '0003_orderdetail_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='t_comment',
        ),
    ]
