# Generated by Django 2.1.4 on 2019-09-10 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('md', '0004_remove_comment_t_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sid',
            new_name='good',
        ),
        migrations.AddField(
            model_name='comment',
            name='fen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_mo',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
